### ISSUE TITLE
Pass custom options to a Morpheus Instance

### ISSUE THREAD

**Issue by tvories** [gomorpheus/terraform-provider-morpheus#1]
Is it possible to pass custom options to the provider?  We have scripts that customize the system based on custom options.

For example, I would like to provision a Morpheus Instance and provide custom options to the resource.  See a code example below of how it might look:

```terraform
resource "morpheus_vsphere_instance" "server2022" {
  name               = "MORPHTFTEST01"
  cloud_id           = data.morpheus_cloud.cloud.id
  group_id           = data.morpheus_group.group.id
  instance_type_id   = data.morpheus_instance_type.instancetype.id
  instance_layout_id = data.morpheus_instance_layout.win2022.id
  plan_id            = data.morpheus_plan.plan.id
  resource_pool_id   = data.morpheus_resource_pool.pool1.id
  environment        = "(3) Development"

  interfaces {
    network_id = data.morpheus_network.vlan200.id
  }

  custom_options {
    puppet_environment = "production"
    puppet_role = "base"
    application = "database"
  }
}
```

**Comment by martezr** [comment]
Custom option support has been added to the provider.

**Comment by tvories** [comment]
@martezr I'm not seeing where it's possible to provide custom options in the docs or in the code.  Can you guide me on how I can add a custom option to a morpheus instance?

**Comment by martezr** [comment]
@tvories The various automation tasks that are supported have an option to specify whether a custom config is available (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/shell_script_task). The provider also supports several option types or inputs (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/text_option_type). If neither of these are what you are looking for then it'd be helpful if you could provide a link to the Morpheus documentation regarding the Morpheus feature that is not available currently in the provider.

**Comment by tvories** [comment]
The reason I opened the issue was to be able to **provide** custom values to a Morpheus instance.  I'll update the issue to hopefully add clarity to the request.
