### ISSUE TITLE
`morpheus_node_type` - extra_options field always causing change

### ISSUE THREAD

**Issue by mbjorgan** [gomorpheus/terraform-provider-morpheus#100]
When importing `morpheus_node_type` the `extra_options` attr is added to the statefile as `null`  (which is correct in a way, since I'm not using it)
Doing a `terraform plan` after the import all node types has a change:
```hcl
~ resource "morpheus_node_type" "RedHat-7-9" {
      + extra_options       = (known after apply)
        id                  = "1273"
        name                = "RedHat 7.9"
        # (7 unchanged attributes hidden)
    }
```

**Comment by martezr** [comment]
I'm having a difficult time reproducing this issue. Is the technology type VMware or another cloud?

**Comment by mbjorgan** [comment]
It's Azure
