### ISSUE TITLE
`morpheus_instance_catalog_item` - Missing attr values on `config` and `visibility`

### ISSUE THREAD

**Issue by mbjorgan** [gomorpheus/terraform-provider-morpheus#102]
When importing `morpheus_instance_catalog_item` that attributes `config` and `visibility` is `null` on all imported catalog items

**Comment by mbjorgan** [comment]
Since the catalog item config json is long, to say the least, would it be possible/smart to extract  `config` as a separate resource?
`morpheus_instance_catalog_item_config` for instance?

**Comment by mbjorgan** [comment]
Not sure how to handle the `config` really... I'm able to import it to the state, no problem. But the config json is big and not imported the same way as it is in the catalog item. So it's causing change.

**Comment by martezr** [comment]
It might be a case of checking if the JSON payloads are equivalent and not necessarily the exact same. I took a quick look at it as when I did the import I was running into whitespace issue. I added my JSON payload to a separate JSON file that I reference using the file function in the Terraform resource.
