### ISSUE TITLE
Importing `morpheus_checkbox_option_type` - mixup of type on attr `default_checked` ?

### ISSUE THREAD

**Issue by mbjorgan** [gomorpheus/terraform-provider-morpheus#107]
In the documentation it says that the `default_checked` is a string with `on` or `off` valid values. In the code on the master branch this field is a bool. Response from the api says `on` if the checkbox is checked and null if it's not.

I have updated the code on my branch now, so that in the statefile it comes in as `true` or `false` and also the resource should contain the same values (true or false).

@martezr is this what we want here? bool true or false, instead of string (on or off)?

**Comment by mbjorgan** [comment]
I'll shoot a PR over, and you can review it to see if this is what you want :)

**Comment by martezr** [comment]
@mbjorgan This one came done to a usability consideration as the use of "on" and "off" strings aren't the most intuitive and using a boolean feels like the most logical way to configured the default_checked attribute. There are also other similar settings in the provider that take this similar approach as well.

**Comment by mbjorgan** [comment]
@martezr Ok. PR #108 does fix a "typo" and should maybe be merged?

**Comment by martezr** [comment]
It does and I certainly appreciate the PR.

**Comment by mbjorgan** [comment]
Fixed in #108
