### ISSUE TITLE
`morpheus_provisioning_workflow` - task order not taken into account

### ISSUE THREAD

**Issue by mbjorgan** [gomorpheus/terraform-provider-morpheus#116]
When importing provisioning workflow tasks in the different phases (config, preProvision etc) are not imported according to task order. 
Tasks in the different phases are added randomly, this causes problems

**Comment by mbjorgan** [comment]
Would it be possible to somehow make use of the `taskOrder` which is in use when creating via UI?

**Comment by martezr** [comment]
The task order is phase agnostic and is the same as the top down order displayed in the UI. From what I've seen as long the task definitions in Terraform mirror the way the appear in the UI then there are no issues.

**Comment by mbjorgan** [comment]
That is correct, we've tested that. The issue is when you import an already existing workflow, then the tasks are placed at random. We've fixed it by manually re-ordering the tasks

**Comment by mbjorgan** [comment]
I've tested this again, creating a new provisioning workflow with a lot of tasks. It is created and displayed in the UI as I expect, but on every plan/apply terraform shows changes on all tasks in the workflow. So this needs attention...

**Comment by martezr** [comment]
Are the tasks that are part of the workflow being managed with the same Terraform or are they being referenced by a data source or ID?

**Comment by mbjorgan** [comment]
Morpheus v5.4.16 and the tasks are a good mix of bash and ansible

**Comment by martezr** [comment]
It looks like the API was updated in 5.5.x and later of the platform to properly sort the tasks returned from the get workflow API call. This meant that when the API was called to set the state the tasks were added out of order even when the tasks were defined in the Terraform in the correct order. Updates have been made to the provider (#127) to fetch the tasks that are part of the workflow but prior to setting the state the tasks are now being sorted based upon the task order attribute. The changes have been tested against 5.4.16 and 6.0.2 to ensure that the changes are compatible with newer versions of the platform.

**Comment by mbjorgan** [comment]
Awesome. When can we see this changes in a release? :)

**Comment by martezr** [comment]
It should be the beginning of next week as I work through a few other issues for the upcoming release.

**Comment by mbjorgan** [comment]
I see, thanks for the update 👍

**Comment by martezr** [comment]
This issue has been addressed with the v0.9.3 release of the Terraform provider.
