### ISSUE TITLE
data "morpheus_integration" does not return a valid id for GIT repos.

### ISSUE THREAD

**Issue by mdemers-cobank** [gomorpheus/terraform-provider-morpheus#130]
This works perfect for my Ansible tasks, but it does not work for script tasks. Could we update this data call to return the correct ID for GIT repos? Or maybe we can create a new data source just for GIT integrations?

data "morpheus_integration" "iam_git" {
  name = "GIT Repo - IAM Team"
}

When creating a script task the wrong ID is used and the task is never mapped to the repo:

repository_id       = data.morpheus_integration.iam_git.id

**Comment by martezr** [comment]
A new `morpheus_git_integration` data source will be created to address how GIT repository IDs are returned. A fix was added recently for the `morpheus_git_integration` resource but a corresponding addition is needed for when Terraform isn't managing the git integration.

**Comment by martezr** [comment]
The new `morpheus_git_integration` data source has been added in the following PR (https://github.com/gomorpheus/terraform-provider-morpheus/pull/132).

**Comment by martezr** [comment]
This issue has been addressed with the `morpheus_git_integration` data source included in the v0.9.3 (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/data-sources/git_integration) release of the Terraform provider.
