### ISSUE TITLE
Identity Source: SAML

### ISSUE THREAD

**Issue by MrYeske-Work** [gomorpheus/terraform-provider-morpheus#140]
One of our highest priorities is full Terraform provider support for Identity Source (SAML).

**Comment by markekibbe** [comment]
+1.

Being able to control Identity Source via IaC methodologies and approaches is huge.

**Comment by martezr** [comment]
This resource has been added in the latest release (v0.9.4) of the provider (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/saml_identity_source).
