### ISSUE TITLE
Referencing virtual image is not working

### ISSUE THREAD

**Issue by ChrisAveniq** [gomorpheus/terraform-provider-morpheus#142]
```
2023-07-07T10:51:48.715+0200 [INFO]  provider.terraform-provider-morpheus_v0.9.3: 2023/07/07 10:51:48 API FAILURE: Response HTTP: 400  Success: false  Size: 105B Body: {"success":false,"msg":"Container Type is invalid","errors":{"virtualImageId":"Virtual Image not found"}} - Container Type is invalid: timestamp=2023-07-07T10:51:48.715+0200

╷
│ Error: Container Type is invalid
│
│   with morpheus_node_type.windows_server_2019_standard,
│   on main.tf line 5, in resource "morpheus_node_type" "windows_server_2019_standard":
│    5: resource "morpheus_node_type" "windows_server_2019_standard" {
│
╵
```

```
data "morpheus_virtual_image" "ngi_template_win_2019" {
  name = "NGI_Template_Win_2019"
}

resource "morpheus_node_type" "windows_server_2019_standard" {
  name             = "Windows Server 2019 Standard"
  short_name       = "windows-server-2019-standard"
  technology       = "vmware"
  version          = "2019"
  category         = "windows"
  virtual_image_id = data.morpheus_virtual_image.ngi_template_win_2019.id

}

```

Running terraform apply without the virtual_image_id, then setting it manually through the UI, and then reapplying works.

Note: the Image is a synced image from vmware.

**Comment by olliephillips** [comment]
Could there have been naming conflicts with other image versions held in the Morpheus Appliance, such that the data source must be referenced on ID to identify it properly? I feel like the name field does not prevent duplicates, so alone, won't be sufficient lookup. I need to check.

**Comment by olliephillips** [comment]
Follow up on this. Not sure related to issue and my previous comment, but discovered name and imagetype as offered in provider are not sufficient to obtain id of image. Duplicates can exist.

**Comment by martezr** [comment]
The `morpheus_virtual_image` datasource now supports defining the image type which can be used to avoid running into issues when there are multiple virtual images with the same name but a different image type.
