### ISSUE TITLE
[Feature Request] Morpheus Cypher Secret Resource

### ISSUE THREAD

**Issue by mark-e-kibbe** [gomorpheus/terraform-provider-morpheus#156]
Morpheus Cypher is utilized in my organization for service catalogue.

Currently workflow for programmatic catalogue deployment is one of the following avenues, all with various pros/cons

- Hand-jamming post catalog item deployment (Not very elegant, and is open to PEBKAC errors)
- Utilizing local exec / shell provider (Lot's of extra code involved there concerning Idempotency)
- Utilizing Before/After Scripts with Terragrunt (Again, Idempotency issues, not the best)

Having a resource block for secret/ Morpheus Cypher would alleviate these issues, nearly bringing full-circle service catalogue capabilities.

**Comment by martezr** [comment]
After taking a look it would make sense to create a resource for the secret and tfvars cypher mount points. This would allow secrets to be written via Terraform. Any updates to the secret would likely force the Terraform resource to be recreated as updating the secret isn't supported by the platform. This would be done in favor of adding in an update behavior in the provider that deletes and recreates the resource behind the scenes.

The examples below is what the resource definition would look like:

```
resource "morpheus_cypher_secret" "secure_password" {
  key    = "apipassword"
  value = "password123"
  lease = 86400
}
```

```
resource "morpheus_cypher_tfvars" "secure_tfvars" {
  key    = "securetfvars"
  value = <<EOT
account=12345
password=supersecure
EOT
  lease = 86400
}
```
