### ISSUE TITLE
XaaS Cloud Resource

### ISSUE THREAD

**Issue by markphelan** [gomorpheus/terraform-provider-morpheus#174]
Would it be possible to manage the XaaS cloud resource type with this provider? At the moment I can't see how to manage a cloud that isn't vsphere/aws/azure.

**Comment by martezr** [comment]
The Morpheus cloud type is not currently supported by the provider but adding support is a quick update.

**Comment by martezr** [comment]
The `morpheus_standard_cloud` resource (https://github.com/gomorpheus/terraform-provider-morpheus/pull/177) has been added and will be available in the next release of the provider.

**Comment by martezr** [comment]
This issue has been addressed in the v0.9.7 of the provider - https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/standard_cloud
