### ISSUE TITLE
`morpheus_workflow_catalog_item` - Support for `visibility` field

### ISSUE THREAD

**Issue by SnathanP** [gomorpheus/terraform-provider-morpheus#175]
Hello,

The [morpheus_workflow_catalog_item](https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/workflow_catalog_item) does not, yet, have a support for the visibility field (public/private) and sets the visibility to private. Nonetheless, [the API already supports this option](https://apidocs.morpheusdata.com/reference/addcatalogitemtype), can it be added as an enhancement?

**Comment by martezr** [comment]
The visibility setting for the `morpheus_workflow_catalog_item` resource (https://github.com/gomorpheus/terraform-provider-morpheus/pull/178) has been added and will available in the next release of the provider.

**Comment by SnathanP** [comment]
> The visibility setting for the `morpheus_workflow_catalog_item` resource (#178) has been added and will available in the next release of the provider.

Hey, thanks for your reactivity @martezr ! :smile:

**Comment by martezr** [comment]
This issue has been fixed in the v0.9.7 release of the Terraform provider - https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/workflow_catalog_item
