### ISSUE TITLE
`Virtual images` scoped to morpheus groups

### ISSUE THREAD

**Issue by amsatique** [gomorpheus/terraform-provider-morpheus#181]
Hello, 

Is it possible to add  some scope mecanism to limit virtual image into groups morpheus ?

Regards

**Comment by martezr** [comment]
Virtual images in the Morpheus platform don't support the ability to scope a virtual image to a Morpheus group which restricts the Terraform provider from provide such functionality. What is the desired functional outcome of this feature?

**Comment by amsatique** [comment]
In our use case, we implement Morpheus `groups` as a logical segmentation within our `tenants`. `Clouds` are linked to `groups`. `Tenant` users can have different levels of rights on groups within the tenant (none, read, read/write, etc). If the client doesn't have access to the group, it can't see the virtual images linked to it.

Hence the importance of implementing this RBAC logic. 

I understand that the feature must be requested from the morpheus repository rather than from the terraform provider repository. Would you prefer me to close this issue and reopen it on the other side?

Regards

**Comment by martezr** [comment]
Yes, please add an idea to the Morpheus Ideas section of the community forum (https://discuss.morpheusdata.com/c/ideas/15).
