### ISSUE TITLE
heredoc on params causes change on every plan/apply

### ISSUE THREAD

**Issue by mbjorgan** [gomorpheus/terraform-provider-morpheus#193]
`morpheus_instance_catalog_item` => content param
`morpheus_manual_option_list` => dataset param

and probably more resources could be worth checking.

When we're using heredoc syntax on params this causes update-in-place on every plan and apply

**Comment by jigeay** [comment]
yes, please correct this issue (might be a regression)

**Comment by martezr** [comment]
This issue has been resolved in the latest release of the provider (https://github.com/gomorpheus/terraform-provider-morpheus/releases/tag/v0.9.8). The mentioned resources were updated along with a handful of others in which heredocs would be used to provide content.
