### ISSUE TITLE
[BUG]resource morpheus_api_option_list lacks of instanceTypeClouds

### ISSUE THREAD

**Issue by jigeay** [gomorpheus/terraform-provider-morpheus#196]
On GUI, we can choose all these options : 
![image](https://github.com/gomorpheus/terraform-provider-morpheus/assets/30889106/ad1be8a1-4858-44b3-abcc-d6acb51340b6)
 but provider can't manage all of them :
`Error: expected option_list to be one of ["clouds" "instanceTypeClouds" "environments" "groups" "instances" "instance-wiki" "networks" "instanceNetworks" "servicePlans" "resourcePools" "securityGroups" "servers" "server-wiki"], got instanceTypeLayouts`

for instance, i need Instance Type Layout
```
resource "morpheus_api_option_list" "azrlayouts" {
  name               = "azrLayouts"
  description        = "Azure Layouts option list"
  labels             = ["vmcreation", "terraform_managed", "azure"]
  visibility         = "private"
  option_list        = "instanceTypeLayouts"
  translation_script = <<SCRIPT
if (input.azrCloud) {
    for (var x = 0; x < data.length; x++) {
        results.push({name:data[x].name + ' ' + data[x].version, value:data[x].id });
    }
}
  SCRIPT

  request_script = <<SCRIPT
    if (input.azrCloud  ) {
      results.zoneId = input.azrCloud.split(':')[0]
      results.siteId  = ${data.morpheus_group.azuregroup.id}
    }
  SCRIPT
}
```

would you please add it ?

best regards,

Matthieu

**Comment by martezr** [comment]
This issue has been resolved in the latest release of the provider (https://github.com/gomorpheus/terraform-provider-morpheus/releases/tag/v0.9.8).
