### ISSUE TITLE
[BUG]morpheus_instance_layout minimum memory

### ISSUE THREAD

**Issue by jigeay** [gomorpheus/terraform-provider-morpheus#197]
Hello team,

A little bug here regarding "minimum memory, which as to be in Go according to the documentation , but, whenever this code is applied,
```
resource "morpheus_instance_layout" "azr_w2019" {
  instance_type_id = morpheus_instance_type.windows.id
  name             = "BEL - AZR -WINDOWS 2019"
  labels           = ["terraform_managed", "azure", "office", "vmcreation"]
  version          = "23.11"
  technology       = "azure"
  minimum_memory   = 2048
  creatable        = true
  option_type_ids  = [morpheus_text_option_type.azrRgIndex.id, morpheus_text_option_type.applicationName.id]
  workflow_id      = morpheus_provisioning_workflow.createrg.id
  node_type_ids = [
    morpheus_node_type.azr_w2019.id
  ]
}

``` 
it seems like the API "answers" in ko, so terraform wants a change : 

```
  # morpheus_instance_layout.azr_w2019 will be updated in-place
  ~ resource "morpheus_instance_layout" "azr_w2019" {
        id                         = "1107"
      ~ minimum_memory             = 2147483648 -> 2048
        name                       = "BEL - AZR -WINDOWS 2019"
        # (10 unchanged attributes hidden)
    }

```
applying this change is fine and everything works in the UI : 

![image](https://github.com/gomorpheus/terraform-provider-morpheus/assets/30889106/c00ddf9e-1e53-4731-8b51-f1dce685f0ce)

thank you for your help

regards,

Matthieu

**Comment by martezr** [comment]
This issue has been resolved in the latest release of the provider (https://github.com/gomorpheus/terraform-provider-morpheus/releases/tag/v0.9.8).
