### ISSUE TITLE
Node type of instance created via terraform not showing monitoring logs after provision

### ISSUE THREAD

**Issue by wabbas-morpheus** [gomorpheus/terraform-provider-morpheus#205]
Looks like the issue is related to the terraform resource type "morpheus_node_type". When the node type is created via Morpheus terraform provider, it's missing the attributes "statTypeCode" and "logTypeCode". For Azure node type, the values for these two attributes needs to be "azure". It's currently not possible to set these values on the latest release of the Morpheus terraform provider.

**Comment by cpdtaylor** [comment]
@martezr this can be closed now I think. Thanks!
