### ISSUE TITLE
Add category to morpheus_workflow_catalog_item resource

### ISSUE THREAD

**Issue by amsatique** [gomorpheus/terraform-provider-morpheus#207]
Hi, 

As an enhancement, can you add the possibility to pass one or more categories to morpheus_workflow_catalog_item through terraform ?

Regards,

**Comment by martezr** [comment]
The `category` attribute has been added to the `morpheus_workflow_catalog_item` resource in the latest resource of the Terraform provider - https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/workflow_catalog_item#category
