### ISSUE TITLE
missing resource to create user_group?

### ISSUE THREAD

**Issue by doubletwist13** [gomorpheus/terraform-provider-morpheus#216]
Am I missing something or is there no resource to create a user group?  And if not, is there a reason or has it just been overlooked and can be added? 

I see a `morpheus_group` resource but that looks like it would create an Infrastructure/resource group?

**Comment by martezr** [comment]
@doubletwist13 You are correct in that there is not currently a resource for Morpheus user groups. It is simply an oversight that can be addressed.

**Comment by doubletwist13** [comment]
In continuing to look into it, it seems there isn't an API call for it either, at least not that I can find.

**Comment by davydotcom** [comment]
User Groups are used solely for creating local user accounts on a machine at provision time. Is this the intended use?

**Comment by davydotcom** [comment]
If so, you are correct I think its a missing API that needs addressed which is easy enough. If not perhaps you are looking for something else like roles. Just want to help lead you down the right path in case this isnt the intent

**Comment by martezr** [comment]
The API endpoint is available in the platform but the documentation for the endpoint is missing. The code has already been added to the Morpheus Golang SDK so the only thing that needs to be done is creating the resource in the Terraform provider.

**Comment by doubletwist13** [comment]
> User Groups are used solely for creating local user accounts on a machine at provision time. Is this the intended use?

Yes, that is the intended use.

**Comment by martezr** [comment]
The `morpheus_user_group` resource has been added in the latest release of the Terraform provider - https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/user_group
