### ISSUE TITLE
add morpheus " storage volume type" data object (Data Source)

### ISSUE THREAD

**Issue by aponchaut** [gomorpheus/terraform-provider-morpheus#232]
Hello,

Could you add a terraform data object to retrieve information about a "storage volume type" based on its ID or Name for example ?

The corresponding REST API is https://apidocs.morpheusdata.com/reference/getstoragevolumetypes .

The minimum interesting information would be :
- id
- name
- code
- category

Regards

**Comment by martezr** [comment]
This feature has been added in the latest release of the provider (v0.9.10).
