### ISSUE TITLE
[bug] morpheus_app_blueprint_catalog_item missing 'visbility' argument/option

### ISSUE THREAD

**Issue by doubletwist13** [gomorpheus/terraform-provider-morpheus#234]
`morpheus_app_blueprint_catalog_item` creates the item with 'private' visbility by default, but doesn't accept a `visibility` argument to be able to specify that it should be public.

**Comment by uthm4n** [comment]
@doubletwist13 I've created a PR to resolve this 😄 

I've tested it and it's working but please wait until the PR has been reviewed before testing it yourself. @martezr had already done the work for this a while ago so shoutout to him.

**Comment by martezr** [comment]
This feature has been added in the latest release of the provider (v0.9.10).
