### ISSUE TITLE
appliance settings

### ISSUE THREAD

**Issue by aponchaut** [gomorpheus/terraform-provider-morpheus#240]
Hello

It's possible to have an equivalent terraform resource to "https://{serverURL}/api/appliance-settings" REST API ?

Regards 
Arnaud

**Comment by olliephillips** [comment]
It looks like the Go SDK supports the calls necessary for this, so it should be possible for you to add this functionality in the provider.

**Comment by martezr** [comment]
This feature has been added in the latest release of the provider (v0.9.10).
