### ISSUE TITLE
Upgrade morpheus_virtual_image (Data Source)

### ISSUE THREAD

**Issue by aponchaut** [gomorpheus/terraform-provider-morpheus#243]
Hello,

Is it possible to add a optional field to select a specific ID (and more) of virtual image research ?

The need comes from the fact that a template image with the same name can be present on several clouds (Error: found X Virtual Images for xxxxxxxxx)

Regards

**Comment by martezr** [comment]
The `morpheus_virtual_image` data source currently supports the ability to scope the search to the ID of the virtual image as well as using the image name and image type. This will align with the Morpheus platform's ability to aggregate images that have the same name and image type underneath the same virtual image.
