### ISSUE TITLE
[Feature]morpheus_task_job 'None' Context type

### ISSUE THREAD

**Issue by jigeay** [gomorpheus/terraform-provider-morpheus#289]
```
resource "morpheus_task_job" "configure_vmware_networks" {
  name                  = "Configure vmware Networks"
  enabled               = true
  labels                = ["terraform_managed", "vmware", "autoconf"]
  task_id               = morpheus_python_script_task.configure_morpheus_vmware_networks.id
  schedule_mode         = "scheduled"
  execution_schedule_id = morpheus_execute_schedule.autoconf.id
  context_type          = "None"
}
```
We cannot use the context_type "none", for jobs executing on the morpheus instance. 
![image](https://github.com/user-attachments/assets/bf604ca4-714a-4b39-8205-bd2cde1813a9)

Could you add it ?

**Comment by martezr** [comment]
The context type setting that aligns with the "None" option in the Morpheus UI is the "appliance" option in the provider. The API expects "appliance" while the UI displays "None".
