### ISSUE TITLE
Add to Terraform provider registry?

### ISSUE THREAD

**Issue by tvories** [gomorpheus/terraform-provider-morpheus#3]
Would it be possible to add this to the official terraform provider registry?

https://www.terraform.io/docs/registry/providers/docs.html#publishing

**Comment by martezr** [comment]
@tvories Work is currently in progress to prepare the provider for submission to the terraform provider registry.

**Comment by martezr** [comment]
The Terraform provider is now available on the Terraform registry - https://registry.terraform.io/providers/gomorpheus/morpheus
