### ISSUE TITLE
Can't get "repository_id" from "morpheus_git_integration" resource for script tasks

### ISSUE THREAD

**Issue by modemers** [gomorpheus/terraform-provider-morpheus#54]
Looking to reference the "repository_id" from the git integration resource ("morpheus_git_integration") for the "morpheus_*_script_task" resource  but property "id" does not work and when I try to reference "repository_id" I get an error.  "morpheus_git_integration" does not seems to have a property called "repository_id" I can use for the script task resources. "${morpheus_git_integration.GitIntegration.repository_id}" does not work.

**Comment by martezr** [comment]
The morpheus_git_integration has a id property that would be passed as the repository_id for one of the task types. The following code block shows a working example in a case in which you are also defining the git integration.

```
resource "morpheus_git_integration" "tf_example_git_integration" {
  name               = "tftest"
  enabled            = true
  url                = "https://github.com/gomorpheus/morpheus-automation-examples"
  default_branch     = "main"
  enable_git_caching = true
}

resource "morpheus_shell_script_task" "tfexample_shell_git" {
  name                = "tfexample_shell_git"
  code                = "tfexample_shell_git"
  source_type         = "repository"
  result_type         = "json"
  script_path         = "Shell/preinstallcheck.sh"
  version_ref         = "main"
  repository_id       = morpheus_git_integration.tf_example_git_integration.id
  sudo                = true
  retryable           = true
  retry_count         = 1
  retry_delay_seconds = 10
  allow_custom_config = true
}
```

If you simply need to reference an existing git integration then you would utilize the morpheus_integration data source (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/data-sources/integration).

**Comment by modemers** [comment]
Thank for you the example! I gave this a try and Im having the same issue. It creates the integration but the task never updates the repository_id. Each time I do a plan or apply it wants to update the repository_id field but doesn't. Im on Morpheus 5.5.1 and here is my provider file:

**Comment by modemers** [comment]
Thank for you the example! I gave this a try and Im having the same issue. It creates the integration but the task never updates the repository_id. Each time I do a plan or apply it wants to update the repository_id field but doesn't. It could be a bug in my version. Im on Morpheus 5.5.1 and here is my provider file:

terraform {
  required_providers {
    morpheus = {
      source  = "gomorpheus/morpheus"
      version = "0.6.0"
    }
  }
}

provider "morpheus" {
  url          = "https://xgndavmorph001.na.cobank2.corp/"
  access_token = "*******"
}

**Comment by martezr** [comment]
I see what you mean now. I'm looking now at how to get the new attribute added that would allow access to the id of the repository which is different than the id of the integration.

**Comment by modemers** [comment]
Found that this API call returns the id needed for the script task to reference the repository: "api/options/codeRepositories"

**Comment by martezr** [comment]
Yeah, that endpoint coupled with passing the integration id as a query parameter will return the code repositories associated with the integration. The integrations will likely add support for the new attribute for code repositories and the tasks will be updated to ensure they're referencing the correct id as well. Looking to get a new release out next week at some point.

**Comment by martezr** [comment]
The latest release (0.7.0) of the provider has added support for exposing a map of repository ids from a git integration to access the repository ID for an integration. Below is an example of how to access the repository ID from a git integration for use with a shell script task.

```
resource "morpheus_git_integration" "tf_shell_integration" {
  name               = "tfgit"
  enabled            = true
  url                = "https://github.com/gomorpheus/morpheus-automation-examples"
  default_branch     = "main"
  enable_git_caching = true
}

resource "morpheus_shell_script_task" "tfexample_shell_git" {
  name                = "tfexample_shell_git"
  code                = "tfexample_shell_git"
  source_type         = "repository"
  result_type         = "json"
  script_path         = "Shell/preinstallcheck.sh"
  version_ref         = "main"
  repository_id       = morpheus_git_integration.tf_shell_integration.repository_ids["morpheus-automation-examples"]
  sudo                = true
  retryable           = true
  retry_count         = 1
  retry_delay_seconds = 10
  allow_custom_config = true
}
```
