### ISSUE TITLE
Enhancement request: Add "morpheus_instance_catalog_item" resource

### ISSUE THREAD

**Issue by modemers** [gomorpheus/terraform-provider-morpheus#55]
Is it possible to add a "morpheus_instance_catalog_item" resource that reads "CONFIG" data from a JSON file? The "CONTENT" could be like "morpheus_workflow_catalog_item" but we would also need inputs.

**Comment by martezr** [comment]
This feature has been added in the last release (0.7.0) of the provider (https://registry.terraform.io/providers/gomorpheus/morpheus/latest/docs/resources/instance_catalog_item).
